name: Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  unitTest:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      ## run unit tests
      - uses: actions/checkout@v2
      - name: Setup JDK version
        uses: actions/setup-java@v2
        with:
          java-version: 11
      - name: Unit tests
        run: sudo bash ./gradlew test --stacktrace

  buildApk:
    name: Build debug apk
    runs-on: ubuntu-latest

    steps:
      ## Initial setup.
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      ## Generate debug apk
      - name: Assemble debug apk
        run: sudo ./gradlew :app:assembleDebug --stacktrace